"""Add microchip fields to Dog model

Revision ID: ddeef9637359
Revises: 
Create Date: 2025-12-30 16:03:35.469003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeef9637359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microchip_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('microchip_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('microchip_id')
        batch_op.drop_column('microchip_company')

    # ### end Alembic commands ###
